/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

extern void initialise_monitor_handles(void);

int main(void)
{
	initialise_monitor_handles();

	printf ("Hello Hell : semi-hosting via OpenOCD x_x\n");

    /* Loop forever */
	for(;;);
}
