/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void executeIllegalInstruction(void)
{
	// Write data bytes in SRAM (0xffffffff - which would get disassembled to an invalid instrcution)
	uint32_t *pSRAM = (uint32_t *)0x20010000;
	*pSRAM = 0xffffffff;

	// create function pointer to data
	uint32_t (*funcPtr)(void);
	funcPtr = (uint32_t *)pSRAM;

	// try to execute illegal instruction - this will trigger usage fault.
	funcPtr();
}

int main(void)
{
	// 1. enable fault handlers via registers (check registers in SCB)
	// SHCSR - system handler control and status register
	uint32_t  *pSHCSR = (uint32_t *) 0xE000ED24;
	*pSHCSR |= (1 << 16);		// enable mem-manage fault
	*pSHCSR |= (1 << 17);		// enable bus fault
	*pSHCSR |= (1 << 18);		// enable usage fault

	// 2. generate faults and analyze under debugger
	executeIllegalInstruction();		// to generate usage fault
}

void HardFault_Handler(void)
{
	printf ("Inside ISR: system exception generated - Hardfault\n");
}

void MemManage_Handler(void)
{
	printf ("Inside ISR: system exception generated - MemManage\n");
}

void BusFault_Handler(void)
{
	printf ("Inside ISR: system exception generated - BusFault\n");
}


__attribute__((naked)) void UsageFault_Handler(void)
{
	__asm volatile ("mrs r0, msp");
	__asm volatile ("b UsageFault_Handler_c");
}

void UsageFault_Handler_c(uint32_t *sp)
{
	//__asm volatile ("mrs r5,msp");
	// register attribute means "do not create this variable on stack", rather
	// use register r0 to hold the value of this variable (msp_value).
	//register uint32_t msp_value __asm("r5");

	// PRINT the CONTEXT saved by processor on stack (when exception is triggered)
	printf ("Inside ISR: system exception generated - UsageFault\n");
	printf ("pBaseStackPointer	: 0x%lx\n", sp);
	printf ("r0					: 0x%lx\n", sp[0]);
	printf ("r1					: 0x%lx\n", sp[1]);
	printf ("r2					: 0x%lx\n", sp[2]);
	printf ("r3					: 0x%lx\n", sp[3]);
	printf ("r12				: 0x%lx\n", sp[4]);
	printf ("LR					: 0x%lx\n", sp[5]);
	printf ("PC					: 0x%lx\n", sp[6]);
	printf ("xpsr				: 0x%lx\n", sp[7]);

}
