/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void standardBitSet(uint8_t *address, int bitPosition)
{
	uint8_t mask = (uint8_t ) (0xff & ~(1 << bitPosition));	// 0x7f is the bit-mask (0111_1111)
	//*address = *address & mask;
/* diassembly (compiler generated)
 24        	*address = *address & mask;
08000200:   ldr     r3, [r7, #4]
08000202:   ldrb    r2, [r3, #0]
08000204:   ldrb    r3, [r7, #15]
08000206:   ands    r3, r2
08000208:   uxtb    r2, r3
0800020a:   ldr     r3, [r7, #4]
0800020c:   strb    r2, [r3, #0]
 */

	__asm volatile (
			"ldr r1, [%0]\n\t"				// load  : r1 = *address
			"and r1, r1, %1\n\t"			// modify: r1 = r1 & 0x80
			"str r1, [%0]\n\t"				// store : *address = r1
			: : "r"(address), "r"(mask):	// 0x7f is the bit-mask (1000_0000)
	);
/* disassembly (inline-asm)
 36        	__asm volatile (
08000200:   ldr     r3, [r7, #4]
08000202:   ldrb    r2, [r7, #15]
08000204:   ldr     r1, [r3, #0]
08000206:   and.w   r1, r1, r2
0800020a:   str     r1, [r3, #0]
 */
}

#define ALIAS_BASE 0x22000000U
#define BIT_BAND_BASE 0x20000000U

void bitBandModification(uint8_t *address, int bitPosition)
{
	uint8_t *alias_address;

	// calculating alias_address of target bit position
	alias_address = (uint8_t *) (ALIAS_BASE + (32 * ((unsigned int )address - BIT_BAND_BASE)) + bitPosition * 4);

	// clear the bit at bitPosition - accessing it just like another variable
	*alias_address = 0;
}

/*
Modify the content of memory location 0x2000_0200 using usual (load-modify-store) and bit-banding method and analyze the difference
    • First store the value 0xff into memory location 0x2000_0200.
    • Then, modify/set the 7th bit position of this location to 0 (using both methods).

Alias address = alias_base  + [ 32 * (bit_band_memory_addr – bit_band_base) ] + bit * 4
Alias address = 0x2200_0000 + [ 32 * (0x2000_0200          – 0x2000_0000) ]   + 7   * 4
 */
int main(void)
{
	uint8_t *byteAddress = (uint8_t *) 0x20000200;
	*byteAddress = 0xff;

	standardBitSet(byteAddress, 7);
	*byteAddress = 0xff;				// reset original value
	bitBandModification(byteAddress, 7);

    /* Loop forever */
	for(;;);
}
