/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

// To find line/IRQ number of USART3 on NVIC, check "Interrrupts and events" section in Reference manual of MCU
#define USART3_IRQNO 39

int main(void)
{
	// check Cortex-M4 Generic User Guide for address locations of NVIC registers
	uint32_t *nvic_ispr1 = (uint32_t *) 0XE000E204;
	uint32_t *nvic_iser1 = (uint32_t *) 0xE000E104;

	// 1. manually set the pending (PEND) bit for USART3 interrupt (IRQ number 39) on NVIC
	// ISPR = Interrupt Set Pending Register
	*nvic_ispr1 = (1 << (USART3_IRQNO % 32));

	// 2. Enable the USART3 interrupt (IRQ number 39) in NVIC
	// This cause USART3 interrupt (in pending state) to get tiggered ?
	// ISER = Interrupt Set Enable Register
	*nvic_iser1 = (1 << (USART3_IRQNO % 32));

    /* Loop forever */
	for(;;);
}

void USART3_IRQHandler(void)
{
	printf ("USART3 Interrupt Handler (IRQHandler)\n");
}

