
.PHONY: clean

all: 1_hello 2_int_var_content 3_returning_pointers


1_hello: 1_hello.c
	gcc $< -o $@

2_int_var_content: 2_int_var_content.c
	gcc $< -o $@

3_returning_pointers: 3_returning_pointers.c
	gcc $< -o $@

clean:
	rm 1_hello 2_int_var_content 3_returning_pointers
